- hosts: node-exporters
  become: yes
  roles:
  - role: prometheus/node_exporter

- hosts: prom-server
  become: yes
  roles:
  - role: docker-io
  - role: prometheus/prometheus-container
  - role: grafana-container
  - role: nginx
